# Generated by Django 4.2 on 2025-02-26 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('loopback_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('vlan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('vlan_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('vlan_subnet_mask', models.PositiveIntegerField(blank=True, default=31, null=True)),
                ('management_ip', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True, protocol='IPv4')),
                ('management_default_gateway', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('routing', models.CharField(choices=[('BGP', 'bgp'), ('OSPF', 'ospf'), ('EIGRP', 'eigrp')], default='BGP', max_length=20)),
                ('vendor', models.CharField(choices=[('arista', 'arista'), ('cisco', 'cisco'), ('juniper', 'juniper')], default='arista', max_length=20)),
                ('ospf_process_id', models.PositiveIntegerField(blank=True, null=True)),
                ('eigrp_as', models.PositiveIntegerField(blank=True, null=True)),
                ('bgp_as_leaf', models.PositiveIntegerField(blank=True, default='0000', null=True)),
                ('ibgp_asn', models.PositiveIntegerField(blank=True, default='0000', null=True)),
                ('bgp_as_spine', models.PositiveIntegerField(blank=True, default='0000', null=True)),
                ('router_id', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True, protocol='IPv4')),
                ('bgp_neighbor_leaf', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True, protocol='IPv4')),
                ('bgp_neighbor_spine1', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True, protocol='IPv4')),
                ('bgp_neighbor_spine2', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True, protocol='IPv4')),
                ('bgp_neighbor_spine3', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True, protocol='IPv4')),
                ('bgp_neighbor_spine4', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True, protocol='IPv4')),
                ('networks', models.JSONField(blank=True, default=dict, null=True)),
                ('device_model', models.CharField(max_length=255)),
                ('network_tier', models.CharField(blank=True, choices=[('leaf', 'leaf'), ('spine', 'spine')], default='leaf', max_length=20, null=True)),
                ('lbcode', models.CharField(blank=True, default='ph01', max_length=255, null=True)),
                ('x_position', models.IntegerField(default=0)),
                ('y_position', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Under Deployment', 'under_deployment'), ('Decommissioned', 'decommissioned')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connections', models.JSONField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_app.device')),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(default='ethernet0', max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('subnet_mask', models.PositiveIntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='device_app.device')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_json', models.JSONField(blank=True, null=True)),
                ('config_path', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topology_configurations', to='device_app.device')),
            ],
        ),
    ]
