# Generated by Django 4.2 on 2025-02-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('under deployment', 'Under_Deployment'), ('decommissioned', 'Decommissioned')], default='active', max_length=20),
        ),
    ]
