# Generated by Django 4.2 on 2025-02-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0002_alter_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('under deployment', 'under_deployment'), ('decommissioned', 'decommissioned')], default='active', max_length=20),
        ),
    ]
