# Generated by Django 4.2 on 2025-02-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0003_alter_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='role',
            field=models.CharField(blank=True, choices=[('layer2', 'layer2'), ('layer3', 'layer3'), ('router', 'router')], default='layer3', max_length=20, null=True),
        ),
    ]
