# Generated by Django 4.2 on 2025-02-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0004_device_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('under deployment', 'under_deployment'), ('decommissioned', 'decommissioned')], default='active', max_length=20, null=True),
        ),
    ]
