# Generated by Django 4.2 on 2025-03-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0007_configuration_logged_user_interface_logged_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('under deployment', 'under_deployment'), ('decommissioned', 'decommissioned')], default='under_deployment', max_length=20, null=True),
        ),
    ]
