# Generated by Django 4.2 on 2025-03-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0010_alter_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(choices=[('arista', 'Arista'), ('cisco', 'Cisco'), ('juniper', 'Juniper')], default='arista', max_length=20),
        ),
    ]
