# Generated by Django 4.2 on 2025-03-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0011_alter_device_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='networks',
            new_name='bgp_networks',
        ),
        migrations.RemoveField(
            model_name='device',
            name='eigrp_as',
        ),
        migrations.RemoveField(
            model_name='device',
            name='routing',
        ),
        migrations.AddField(
            model_name='device',
            name='ospf_networks',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(choices=[('arista', 'arista'), ('cisco', 'cisco'), ('juniper', 'juniper')], default='arista', max_length=20),
        ),
    ]
