# Generated by Django 4.2 on 2025-03-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0012_rename_networks_device_bgp_networks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='management_mac_add',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='bgp_networks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='device',
            name='ospf_networks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
