# Generated by Django 4.2 on 2025-07-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0013_device_management_mac_add_alter_device_bgp_networks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='bgp_as_leaf',
            field=models.PositiveIntegerField(blank=True, default='64513', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='bgp_as_spine',
            field=models.PositiveIntegerField(blank=True, default='64512', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='bgp_networks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ibgp_asn',
            field=models.PositiveIntegerField(blank=True, default='64513', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ospf_networks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
