# Generated by Django 4.2 on 2025-07-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0014_maccounter_alter_device_bgp_as_leaf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='management_mac_add',
            new_name='management_mac_address',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='ip',
        ),
        migrations.AddField(
            model_name='interface',
            name='interface_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interface',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='subnet_mask',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
