# Generated by Django 4.2 on 2025-07-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0015_rename_management_mac_add_device_management_mac_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='management_mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
