# Generated by Django 4.2 on 2025-07-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0016_alter_device_management_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='bgp_as_leaf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='bgp_as_spine',
            field=models.PositiveIntegerField(blank=True, default=64512, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ibgp_asn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
