# Generated by Django 4.2 on 2025-03-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
