# Generated by Django 4.2 on 2025-03-02 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0002_useractivitylog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logged_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logged_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
