# Generated by Django 4.2 on 2025-03-03 15:20

from django.db import migrations, models
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_profile_logged_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='user_app/default.png', upload_to=user_app.models.user_directory_path),
        ),
    ]
