# Generated by Django 4.2 on 2025-03-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='logged_user',
        ),
    ]
