# Generated by Django 4.2 on 2025-03-17 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0010_alter_device_status'),
        ('user_app', '0006_remove_profile_logged_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='device_app.device'),
        ),
    ]
