# Generated by Django 4.2 on 2025-03-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_useractivitylog_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_id',
            field=models.CharField(default='default_login_id', editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
