"""
Django settings for NetAutoServ project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3ccf&#5foq(sfmc)2k$(8e&+v6t))3%x(f@anqau@hs=de%ogl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.0.15"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'ndas_app',
    'user_app',
    'device_app',
    'naas_app',
    'emulator_app',
    'compliance_app',
    'bug_tracker',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NetAutoServ.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/"templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NetAutoServ.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databasescls

load_dotenv()  # take environment variables from .env file
DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("MYSQL_DB"),
        "USER": os.getenv("MYSQL_USER"),
        "PASSWORD": os.getenv("MYSQL_PASSWORD"),
        "HOST": os.getenv("MYSQL_HOST"),
        "PORT": os.getenv("MYSQL_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
#this should be a tuple
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REDIRECT_URL = '/dashboard/'
LOGIN_URL = '/login/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# For all other emails (or use the same account)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("MAIL_HOST")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PW_RESET")
DEFAULT_FROM_EMAIL = "NDAS Email Confirmation"

SITE_NAME = "NDAS"
SUPPORT_EMAIL = os.getenv("NDAS_EMAIL_SUPPORT")

# Additional email credentials for password reset
EMAIL_PW_RESET_USER = os.getenv("MAIL_HOST")  # Email account used for password reset
EMAIL_PW_RESET_PASS = os.getenv("EMAIL_PW_RESET")  # Password for the email account used for password resets

# SME_EMAILS = ["herpidz06@gmail.com", "ejnavarro06@gmail.com"]

# DHCP Server Configuration
DHCP_SERVER = os.getenv("DHCP_SERVER")                  # my remote Ubuntu DHCP server
DHCP_SSH_USER = os.getenv("DHCP_SSH_USER")              # SSH user with sudo privileges
DHCP_SSH_KEY_PATH = os.getenv("DHCP_SSH_KEY")           # SSH key path
DHCP_SSH_PASSWORD = os.getenv("DHCP_SSH_PASSWORD")      # SSH password for the user
DHCP_SSH_PORT = os.getenv("DHCP_SSH_PORT")              # SSH port for the user
TFTP_SERVER = os.getenv("TFTP_SERVER")                  #  remote TFTP server IP
