# Generated by Django 4.2 on 2025-02-26 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmulatorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('STOPPED', 'STOPPED')], max_length=20)),
                ('ssh_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ssh_port', models.IntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_app.device')),
            ],
        ),
        migrations.CreateModel(
            name='DevicePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.FloatField(default=0)),
                ('y_position', models.FloatField(default=0)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='device_app.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_interface', models.CharField(default='eth0', max_length=20)),
                ('target_interface', models.CharField(default='eth0', max_length=20)),
                ('network_name', models.CharField(default='net1', max_length=100)),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_out', to='device_app.device')),
                ('target_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_in', to='device_app.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_1_configurations', to='device_app.device')),
                ('device_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_2_configurations', to='device_app.device')),
            ],
        ),
    ]
