# Generated by Django 4.2 on 2025-03-17 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emulator_app', '0002_deviceconfiguration_logged_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emulatorsession',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emulatorsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emulatorsession',
            name='last_started',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 17, 1, 30, 54, 257369, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emulatorsession',
            name='start_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emulatorsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emulatorsession',
            name='total_tested_devices',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
