# Generated by Django 4.2 on 2025-03-01 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device_app', '0005_alter_device_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated_on', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.BooleanField(default=False)),
                ('qsfp', models.BooleanField(default=False)),
                ('ribd', models.BooleanField(default=False)),
                ('multi_agent', models.BooleanField(default=False)),
                ('eos_code', models.BooleanField(default=False)),
                ('mac_timer', models.BooleanField(default=False)),
                ('stp', models.BooleanField(default=False)),
                ('ntp', models.BooleanField(default=False)),
                ('ip_routing', models.BooleanField(default=False)),
                ('vlan_4001', models.BooleanField(default=False)),
                ('svi_vlan4001', models.BooleanField(default=False)),
                ('port_channel100', models.BooleanField(default=False)),
                ('ospf', models.BooleanField(default=False)),
                ('ospf_id', models.BooleanField(default=False)),
                ('eigrp', models.BooleanField(default=False)),
                ('eigrp_as', models.BooleanField(default=False)),
                ('static', models.BooleanField(default=False)),
                ('bgp_as', models.BooleanField(default=False)),
                ('router_id', models.BooleanField(default=False)),
                ('bgp_neighbor', models.BooleanField(default=False)),
                ('bgp_network', models.BooleanField(default=False)),
                ('bgp_max_path', models.BooleanField(default=False)),
                ('loopback0', models.BooleanField(default=False)),
                ('mgmt1_intf', models.BooleanField(default=False)),
                ('mgmt1_route', models.BooleanField(default=False)),
                ('l3_uplink_to_spine1', models.BooleanField(default=False)),
                ('l3_uplink_to_spine2', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_app.device')),
            ],
        ),
    ]
