# Generated by Django 4.2 on 2025-03-02 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('naas_app', '0002_automationrun_logged_user_configuration_logged_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='logged_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='naas_configurations', to=settings.AUTH_USER_MODEL),
        ),
    ]
