# Generated by Django 4.2 on 2025-07-13 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubnetBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=18, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subnet Block',
                'verbose_name_plural': 'Subnet Blocks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubnetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(max_length=18)),
                ('subnet_type', models.CharField(choices=[('loopback', 'Loopback'), ('point_to_point', 'Point-to-Point'), ('data_vlan', 'Data VLAN'), ('voice_vlan', 'Voice VLAN'), ('server_vlan', 'Server VLAN'), ('unassigned', 'Unassigned')], max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('subnet_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ip_addressing.subnetblock')),
            ],
            options={
                'verbose_name': 'Subnet Assignment',
                'verbose_name_plural': 'Subnet Assignments',
                'ordering': ['subnet'],
                'unique_together': {('subnet_block', 'subnet')},
            },
        ),
    ]
