# Generated by Django 4.2 on 2025-07-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_addressing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnetassignment',
            name='subnet_type',
            field=models.CharField(choices=[('management', 'Management'), ('loopback', 'Loopback'), ('point_to_point', 'Point-to-Point'), ('data_vlan', 'Data VLAN'), ('voice_vlan', 'Voice VLAN'), ('server_vlan', 'Server VLAN'), ('unassigned', 'Unassigned')], max_length=20),
        ),
    ]
